plugins {
    id 'com.github.johnrengelman.shadow' version '8.1.1'
    id 'java'
    id 'application'
}

var group = "de.zonlykroks"
var id = "classfilemixins"
var ver = "0.1-SNAPSHOT"

application {
    mainClassName = 'de.zonlykroks.classfilemixins.Entrypoint'
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs += "--enable-preview"
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.json:json:20250107'
    implementation("commons-cli:commons-cli:1.9.0")
    implementation 'com.github.spotbugs:spotbugs-annotations:4.8.6'
    implementation("org.apache.commons:commons-lang3:3.17.0")
}

jar {
    manifest {
        attributes 'Main-Class': 'de.zonlykroks.classfilemixins.Entrypoint'
    }
}
